# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainkxdavc.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
                            QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
                           QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
                           QRadialGradient)
from PySide2.QtWidgets import *

# import resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1429, 872)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(860, 650))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(94, 94, 94, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(111, 111, 111, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(77, 77, 77, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(50, 50, 50, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        brush6 = QBrush(QColor(235, 235, 235, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush7 = QBrush(QColor(113, 255, 19, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush7)
        brush8 = QBrush(QColor(191, 236, 194, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush9 = QBrush(QColor(62, 62, 62, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush10 = QBrush(QColor(235, 235, 235, 128))
        brush10.setStyle(Qt.SolidPattern)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
        # endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
        # endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.SolidPattern)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
        # endif
        MainWindow.setPalette(palette)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks | QMainWindow.AnimatedDocks)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(255)
        sizePolicy1.setVerticalStretch(255)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.main = QFrame(self.centralwidget)
        self.main.setObjectName(u"main")
        self.main.setGeometry(QRect(-9, -14, 1451, 901))
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy2)
        self.verticalLayout = QVBoxLayout(self.main)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetMaximumSize)
        self.header = QFrame(self.main)
        self.header.setObjectName(u"header")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(255)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy3)
        self.header.setMinimumSize(QSize(0, 60))
        self.header.setMaximumSize(QSize(16777215, 50))
        self.header.setFrameShape(QFrame.StyledPanel)
        self.header.setLineWidth(10)
        self.header.setMidLineWidth(10)
        self.horizontalLayout = QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.header_icon = QLabel(self.header)
        self.header_icon.setObjectName(u"header_icon")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(1)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.header_icon.sizePolicy().hasHeightForWidth())
        self.header_icon.setSizePolicy(sizePolicy4)
        self.header_icon.setMinimumSize(QSize(47, 47))
        self.header_icon.setMaximumSize(QSize(50, 50))
        palette1 = QPalette()
        brush12 = QBrush(QColor(34, 255, 0, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush12)
        brush13 = QBrush(QColor(193, 193, 193, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush1)
        brush14 = QBrush(QColor(88, 88, 88, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush14)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush15 = QBrush(QColor(68, 68, 68, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush15)
        brush16 = QBrush(QColor(46, 255, 0, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush16)
        brush17 = QBrush(QColor(58, 255, 24, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush17)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush18 = QBrush(QColor(42, 42, 41, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush18)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush19 = QBrush(QColor(255, 255, 255, 128))
        brush19.setStyle(Qt.SolidPattern)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
        # endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush14)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush15)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush17)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush18)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
        # endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush15)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush18)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
        # endif
        self.header_icon.setPalette(palette1)
        font = QFont()
        font.setFamily(u"Proxima Nova Rg")
        font.setPointSize(28)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.header_icon.setFont(font)
        self.header_icon.setAutoFillBackground(True)

        self.horizontalLayout.addWidget(self.header_icon)

        self.header_text = QLabel(self.header)
        self.header_text.setObjectName(u"header_text")
        sizePolicy3.setHeightForWidth(self.header_text.sizePolicy().hasHeightForWidth())
        self.header_text.setSizePolicy(sizePolicy3)
        self.header_text.setMinimumSize(QSize(0, 46))
        self.header_text.setMaximumSize(QSize(16777215, 50))
        palette2 = QPalette()
        brush20 = QBrush(QColor(43, 213, 97, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush20)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush14)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush16)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush17)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush18)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
        # endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush20)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush17)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush18)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
        # endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
        # endif
        self.header_text.setPalette(palette2)
        self.header_text.setFont(font)
        self.header_text.setLayoutDirection(Qt.LeftToRight)
        self.header_text.setAutoFillBackground(True)

        self.horizontalLayout.addWidget(self.header_text)

        self.verticalLayout.addWidget(self.header)

        self.main_window = QHBoxLayout()
        self.main_window.setObjectName(u"main_window")
        self.side_panel = QFrame(self.main)
        self.side_panel.setObjectName(u"side_panel")
        sizePolicy5 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(1)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.side_panel.sizePolicy().hasHeightForWidth())
        self.side_panel.setSizePolicy(sizePolicy5)
        self.side_panel.setFrameShape(QFrame.StyledPanel)
        self.side_panel.setLineWidth(6)
        self.side_panel.setMidLineWidth(6)
        self.sidebar = QVBoxLayout(self.side_panel)
        self.sidebar.setObjectName(u"sidebar")
        self.label = QLabel(self.side_panel)
        self.label.setObjectName(u"label")
        sizePolicy6 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy6)
        self.label.setMinimumSize(QSize(150, 0))
        self.label.setMaximumSize(QSize(250, 30))
        palette3 = QPalette()
        brush21 = QBrush(QColor(30, 215, 96, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush21)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush21)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush21)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush21)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush21)
        self.label.setPalette(palette3)
        font1 = QFont()
        font1.setFamily(u"Proxima Nova Rg")
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.label.setFont(font1)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QFrame.StyledPanel)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(5)

        self.sidebar.addWidget(self.label)

        self.label_2 = QLabel(self.side_panel)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(150, 0))
        self.label_2.setMaximumSize(QSize(250, 30))
        self.label_2.setFont(font1)
        self.label_2.setFrameShape(QFrame.StyledPanel)
        self.label_2.setLineWidth(5)
        self.label_2.setMidLineWidth(5)

        self.sidebar.addWidget(self.label_2)

        self.label_3 = QLabel(self.side_panel)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMinimumSize(QSize(150, 0))
        self.label_3.setMaximumSize(QSize(250, 30))
        self.label_3.setFont(font1)
        self.label_3.setFrameShape(QFrame.StyledPanel)
        self.label_3.setLineWidth(5)
        self.label_3.setMidLineWidth(5)

        self.sidebar.addWidget(self.label_3)

        self.label_4 = QLabel(self.side_panel)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(150, 0))
        self.label_4.setMaximumSize(QSize(250, 30))
        self.label_4.setFont(font1)
        self.label_4.setFrameShape(QFrame.StyledPanel)
        self.label_4.setLineWidth(5)
        self.label_4.setMidLineWidth(5)

        self.sidebar.addWidget(self.label_4)

        self.label_5 = QLabel(self.side_panel)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(150, 0))
        self.label_5.setMaximumSize(QSize(250, 30))
        self.label_5.setFont(font1)
        self.label_5.setFrameShape(QFrame.StyledPanel)
        self.label_5.setLineWidth(5)
        self.label_5.setMidLineWidth(5)

        self.sidebar.addWidget(self.label_5)

        self.line = QFrame(self.side_panel)
        self.line.setObjectName(u"line")
        self.line.setEnabled(True)
        sizePolicy7 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy7)
        self.line.setMinimumSize(QSize(0, 0))
        self.line.setMaximumSize(QSize(0, 16777215))
        self.line.setAutoFillBackground(False)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.sidebar.addWidget(self.line)

        self.label_6 = QLabel(self.side_panel)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(150, 0))
        self.label_6.setMaximumSize(QSize(250, 30))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush22 = QBrush(QColor(235, 7, 11, 255))
        brush22.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush22)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush23 = QBrush(QColor(206, 0, 0, 255))
        brush23.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush23)
        brush24 = QBrush(QColor(102, 0, 0, 255))
        brush24.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush24)
        brush25 = QBrush(QColor(152, 123, 246, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush25)
        brush26 = QBrush(QColor(235, 7, 11, 128))
        brush26.setStyle(Qt.NoBrush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush26)
        # endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush22)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush23)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush24)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush25)
        brush27 = QBrush(QColor(235, 7, 11, 128))
        brush27.setStyle(Qt.NoBrush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush27)
        # endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush23)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush23)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush24)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush25)
        brush28 = QBrush(QColor(235, 7, 11, 128))
        brush28.setStyle(Qt.NoBrush)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush28)
        # endif
        self.label_6.setPalette(palette4)
        self.label_6.setFont(font1)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setFrameShape(QFrame.StyledPanel)
        self.label_6.setFrameShadow(QFrame.Plain)
        self.label_6.setLineWidth(5)
        self.label_6.setMidLineWidth(5)

        self.sidebar.addWidget(self.label_6)

        self.main_window.addWidget(self.side_panel)

        self.main_view = QFrame(self.main)
        self.main_view.setObjectName(u"main_view")
        sizePolicy8 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy8.setHorizontalStretch(4)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.main_view.sizePolicy().hasHeightForWidth())
        self.main_view.setSizePolicy(sizePolicy8)
        self.main_view.setFrameShape(QFrame.StyledPanel)
        self.main_view.setLineWidth(7)
        self.main_view.setMidLineWidth(7)
        self.verticalLayout_2 = QVBoxLayout(self.main_view)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.graoh_view = QFrame(self.main_view)
        self.graoh_view.setObjectName(u"graoh_view")
        sizePolicy9 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(3)
        sizePolicy9.setHeightForWidth(self.graoh_view.sizePolicy().hasHeightForWidth())
        self.graoh_view.setSizePolicy(sizePolicy9)
        self.horizontalLayout_2 = QHBoxLayout(self.graoh_view)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.frame = QFrame(self.graoh_view)
        self.frame.setObjectName(u"frame")
        sizePolicy10 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy10.setHorizontalStretch(2)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy10)
        palette5 = QPalette()
        brush29 = QBrush(QColor(55, 172, 104, 255))
        brush29.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush29)
        brush30 = QBrush(QColor(134, 179, 50, 255))
        brush30.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush30)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush29)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush30)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush30)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush30)
        self.frame.setPalette(palette5)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(6)
        self.frame.setMidLineWidth(6)

        self.horizontalLayout_2.addWidget(self.frame)

        self.verticalFrame = QFrame(self.graoh_view)
        self.verticalFrame.setObjectName(u"verticalFrame")
        sizePolicy5.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy5)
        self.verticalFrame.setFrameShape(QFrame.StyledPanel)
        self.verticalFrame.setLineWidth(6)
        self.verticalFrame.setMidLineWidth(6)
        self.verticalLayout_3 = QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)

        self.horizontalLayout_2.addWidget(self.verticalFrame)

        self.verticalLayout_2.addWidget(self.graoh_view)

        self.top_stats = QFrame(self.main_view)
        self.top_stats.setObjectName(u"top_stats")
        sizePolicy11 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(2)
        sizePolicy11.setHeightForWidth(self.top_stats.sizePolicy().hasHeightForWidth())
        self.top_stats.setSizePolicy(sizePolicy11)
        self.top_stats.setLayoutDirection(Qt.LeftToRight)
        self.top_stats.setFrameShape(QFrame.StyledPanel)
        self.top_stats.setLineWidth(6)
        self.top_stats.setMidLineWidth(6)
        self.horizontalLayout_3 = QHBoxLayout(self.top_stats)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_2 = QFrame(self.top_stats)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy6.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy6)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_3.addWidget(self.frame_2)

        self.sizegrip = QFrame(self.top_stats.sizegrip)
        self.sizegrip.setObjectName(u"sizegrip")
        sizePolicy12 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy12.setHorizontalStretch(0)
        sizePolicy12.setVerticalStretch(0)
        sizePolicy12.setHeightForWidth(self.sizegrip.sizePolicy().hasHeightForWidth())
        self.sizegrip.setSizePolicy(sizePolicy12)
        self.sizegrip.setMinimumSize(QSize(25, 20))
        self.sizegrip.setMaximumSize(QSize(20, 20))
        self.sizegrip.setLayoutDirection(Qt.LeftToRight)
        self.sizegrip.setFrameShape(QFrame.StyledPanel)
        self.sizegrip.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_3.addWidget(self.sizegrip, 0, Qt.AlignLeft | Qt.AlignBottom)

        self.verticalLayout_2.addWidget(self.top_stats)

        self.main_window.addWidget(self.main_view)

        self.verticalLayout.addLayout(self.main_window)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)



    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Spotify Data View", None))
        self.header_icon.setText(QCoreApplication.translate("MainWindow",
                                                            u"<html><head/><body><p><img src=\":/icons/spotify-icon.png\" height=\"50\"/></p><p><br/></p></body></html>",
                                                            None))
        self.header_text.setText(QCoreApplication.translate("MainWindow",
                                                            u"<html><head/><body><p><span style=\" color:#1ed760;\">Spotify Data View</span></p></body></html>",
                                                            None))
        self.label.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Overview</p></body></html>", None))
        self.label_2.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Favourites</p></body></html>", None))
        self.label_3.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Listening Habits</p></body></html>", None))
        self.label_4.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Genre Profiling</p></body></html>", None))
        self.label_5.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>All Stats</p></body></html>", None))
        self.label_6.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Exit</p></body></html>", None))


    # retranslateUi


